### ISSUE TITLE
help me please，error:object is not a function

### ISSUE THREAD

**Issue by Aton5859** [AGENTxXx/cordova-plugin-zip#1]
I copy your code into my project and report an error:
"TypeError: Object(...) is not a function
    at Zip.unzip (file:///android_asset/www/build/vendor.js:75159:145)
    at HomePage.webpackJsonp.197.HomePage.unZip (file:///android_asset/www/build/main.js:322:22)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:145:31)
    at handleEvent (file:///android_asset/www/build/vendor.js:13558:172)
    at callWithDebugContext (file:///android_asset/www/build/vendor.js:15043:42)
    at Object.debugHandleEvent [as handleEvent] (file:///android_asset/www/build/vendor.js:14630:12)
    at dispatchEvent (file:///android_asset/www/build/vendor.js:10007:25)
    at file:///android_asset/www/build/vendor.js:10621:38
    at HTMLButtonElement.<anonymous> (file:///android_asset/www/build/vendor.js:36330:53)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)"

 Can you tell me what the problem is? If you can answer me,I sehell be very grateful!

**Comment by AGENTxXx** [comment]
Hi! Your error does not contain information about the problem in unZip. Show me your code with unZip lines. If you are Russian, write in Russian.

**Comment by Aton5859** [comment]
Hello, I have solved this problem. Thank you. I am Chinese.

**Comment by Aton5859** [comment]
@AGENTxXx Hello, I have solved this problem. Thank you. I am Chinese.
